### ISSUE TITLE
Update website repo link and archive GitHub repo

### ISSUE THREAD

**Issue by mirdaki** [KombuchaPrivacy/circles-ios#1]
Hey, I noticed the GitLab seems to be the active repo for this project even though the website still links to this GitHub org. Would you consider updating the website to point to the new repo and adding a note to this GitHub page about it or marking it as archived?

**Comment by mirdaki** [comment]
@cvwright gentle ping

**Comment by cvwright** [comment]
Hey, thanks for the reminder.  I'm finally getting around to cleaning things up.
